matlab_file:
  path: 'C:\PROGRAMACION\PENDULO INVERTIDO\Pendulo Invertido Diego\Matlab-Furuta-Pendulum\Simulink\dataAcquisition\synthetic_data.mat'
  data_name: 'data'
  columns_name:
    - 'time'
    - 'set_point_rotary_arm'
    - 'control_law'
    - 'position_rotary_arm'
    - 'position_pendulum_wrapped'
    - 'speed_rotary_arm'
    - 'speed_pendulum'
    - 'position_pendulum'

data_inserter:
  table: 'tests'