mat_file:
  path: 'C:\PROGRAMACION\PENDULO INVERTIDO\Pendulo Invertido Diego\Matlab-Furuta-Pendulum\Simulink\dataAcquisition\synthetic_data.mat'
  data_name: 'data'
  columns_name:
    - 'time'
    - 'set_point_rotary_arm'
    - 'control_law'
    - 'position_rotary_arm'
    - 'position_pendulum_wrapped'
    - 'speed_rotary_arm'
    - 'speed_pendulum'
    - 'position_pendulum'

drop_time_column: False

save_file:
  path: 'C:\PROGRAMACION\PENDULO INVERTIDO\Pendulo Invertido Diego\Python-Furuta-Pendulum\data\datasets'
  file_name: 'synthetic_data2.parquet'
