stages:
  data_reader:
    cmd: python source/data_reader.py
    deps:
      - source/data_interface.py
      - source/data_reader.py
    params:
      - config/parameters.yaml:
          - data_reader.save_path
          - data_reader.file_name
          - data_reader.table
          - data_reader.columns
