reader:
  file_name: 'real_data_swing_up.parquet'
  columns:
    - 'control_law'
    - 'position_rotary_arm'
    - 'position_pendulum_wrapped'
    - 'speed_rotary_arm'
    - 'speed_pendulum'

splitter:
  target:
    - 'control_law'
  shuffle: False
  validation_size: 0.2
  test_size: 0.2

scaler:
  type: 'min_max'
  scale_range: (0, 1)

callbacks:
  - early_stopping:
      monitor: 'val_loss'
      patience: 10
      restore_best_weights: True
  - checkpoint:
      monitor: 'val_loss'
      save_best_only: True
      save_weights_only: True
      mode: 'min'
      filepath: 'model.h5'