matlab_controller:
  file_name: 'synthetic_data_stabilization.mat'
  data_name: 'data'
  columns_name:
    - 'time'
    - 'set_point_rotary_arm'
    - 'control_law'
    - 'position_rotary_arm'
    - 'position_pendulum_wrapped'
    - 'speed_rotary_arm'
    - 'speed_pendulum'
    - 'position_pendulum'

inserter:
  file_name: 'synthetic_data_stabilization_test'
  extension: 'parquet'

reader:
  file_name: 'stabilization_synthetic_data'
  extension: 'parquet'
  columns:
    - 'set_point_rotary_arm'
    - 'control_law'
    - 'position_rotary_arm'
    - 'position_pendulum_wrapped'
    - 'speed_rotary_arm'
    - 'speed_pendulum'

splitter:
  target:
    - 'control_law'
  shuffle: False
  validation_size: 0.2
  test_size: 0.2