raw_dataset:
  matlab:
    file_name: 'real_data_swing_up.mat'
    data: 'data'
    columns:
      - 'time'
      - 'set_point_rotary_arm'
      - 'control_law'
      - 'position_rotary_arm'
      - 'position_pendulum_wrapped'
      - 'speed_rotary_arm'
      - 'speed_pendulum'
      - 'position_pendulum'
  saver:
    dataset_name: 'real_data_swing_up.parquet'

neural_network_model:
  build:
    model_type: 'dense'
    input_shape: 8
    number_units: [8, 4, 2, 1]
    activation_hidden_layers: 'tanh'
    activation_output_layer: 'linear'
  compile:
    loss: 'mae'
    metrics: ['mse']
    optimizer: 'adam'
    learning_rate: 0.001
#  epochs: 100
#  batch_size: 32
#  verbose: 1