matlab_controller:
  file_name: 'synthetic_data_stabilization.mat'
  data_name: 'data'
  columns_name:
    - 'time'
    - 'set_point_rotary_arm'
    - 'control_law'
    - 'position_rotary_arm'
    - 'position_pendulum_wrapped'
    - 'speed_rotary_arm'
    - 'speed_pendulum'
    - 'position_pendulum'

data_saver:
  file_name: 'synthetic_data_stabilization_test'
  extension: 'parquet'

data_reader:
  file_name: 'synthetic_data_stabilization_test'
  extension: 'parquet'
  columns:
    - 'set_point_rotary_arm'
    - 'control_law'
    - 'position_rotary_arm'
    - 'position_pendulum_wrapped'
    - 'speed_rotary_arm'
    - 'speed_pendulum'
