matlab_data:
  file_name:
    - 'stabilization_disturbance_5'
    - 'stabilization_ideal'
  source: 'synthetic'
  data_name: 'data'
  columns:
    - 'time'
    - 'set_point_rotary_arm'
    - 'control_law'
    - 'position_rotary_arm'
    - 'position_pendulum_wrapped'
    - 'speed_rotary_arm'
    - 'speed_pendulum'
    - 'position_pendulum'

dataset:
  create_dataset: True
  save_dataset: True
  name: 'stabilization_disturbance_5'
  shuffle_data: True
  window_length: 400

model:
  architecture:
    model_type: 'dense'
    input_shape: 6
    number_units: [16, 8, 4, 1]
    activation_hidden_layers: 'relu'
    activation_output_layer: 'linear'
  optimizer:
    optimizer_type: 'sgd'
    learning_rate: 0.01
  loss:
    - 'mse'
  metrics:
    - 'mse'
    - 'mae'
    - 'r2'

callbacks:
    early_stopping:
      monitor: 'val_loss'
      patience: 12
      restore_best_weights: True
      verbose: 1
    model_checkpoint:
      filepath: '/temp/checkpoints'
      monitor: 'val_loss'
      save_best_only: True
    reduce_lr:
      monitor: 'val_loss'
      factor: 0.02
      patience: 4
      verbose: 1
    tensor_board:
      log_dir: '/temp/tensor_board_logs'
      write_graph: True
      write_images: True

training:
  model_name: 'aaaaa'
  retrain: False
  features:
    - 'position_rotary_arm'
    - 'position_pendulum_wrapped'
    - 'speed_rotary_arm'
    - 'speed_pendulum'
  target:
    - 'control_law'
  test_size: 20
  validation_size: 30
  epochs: 100
  batch_size: 32
  verbose: 1