data:
  matlab:
    file_name: 'stabilization_disturbance_5.mat'
    source: 'synthetic'
    data: 'data'
    columns:
      - 'time'
      - 'set_point_rotary_arm'
      - 'control_law'
      - 'position_rotary_arm'
      - 'position_pendulum_wrapped'
      - 'speed_rotary_arm'
      - 'speed_pendulum'
      - 'position_pendulum'
  dataset:
    name: 'synthetic_data_stabilization_disturbance_2'
    folder_to_save: 'datasets'
    shuffle_data: True
    window_length: 400

model:
  architecture:
    model_type: 'dense'
    input_shape: 6
    number_units: [16, 8, 4, 1]
    activation_hidden_layers: 'relu'
    activation_output_layer: 'linear'
  optimizer:
    optimizer_type: 'sgd'
    learning_rate: 0.01
  loss:
    - 'mse'
  metrics:
    - 'mse'
    - 'mae'
    - 'r2'

learning:
  training:
    retrain: False
    features:
      - 'position_rotary_arm'
      - 'position_pendulum_wrapped'
      - 'speed_rotary_arm'
      - 'speed_pendulum'
    target:
      - 'control_law'
    test_size: 20
    validation_size: 30
    epochs: 100
    batch_size: 32
    verbose: 1
  callbacks:
    early_stopping:
        monitored_val: 'val_loss'
        patience: 5
        restore_best_weights: True
        verbose: 1
    model_checkpoint:
        path: '/temp/checkpoints'
        monitored_val: 'val_loss'
        save_best: True
    tensor_board:
        log_dir: '/temp/tensor_boards_logs/'
        write_graph: True
        write_images: True
