raw_dataset:
  matlab:
    file_name: 'real_data_swing_up.mat'
    data: 'data'
    columns:
      - 'time'
      - 'set_point_rotary_arm'
      - 'control_law'
      - 'position_rotary_arm'
      - 'position_pendulum_wrapped'
      - 'speed_rotary_arm'
      - 'speed_pendulum'
      - 'position_pendulum'
  saver:
    dataset_name: 'real_data_swing_up.parquet'